FROM python:3.11.3
WORKDIR /app
COPY requirements.txt /app/
RUN pip install -r requirements.txt
COPY . /app/
EXPOSE 8000
ENV DJANGO_SETTINGS_MODULE=myproject.settings
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]